### ISSUE TITLE
秘籍大全前端相关

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bps#10]
![image](https://user-images.githubusercontent.com/8476969/134224878-d4a889de-d6f1-491a-b138-646b60da29e8.png)

使用element table

展示数据中的各个项（以接口数据最终为准，自行优化）

**Comment by iRuxu** [comment]
前端文件位置：
src/views/Recipe.vue

关联左侧心法筛选时，显示对应门派的秘籍
没有心法时，或通用时显示江湖的秘籍

**Comment by iRuxu** [comment]
心法与门派依赖关系：
https://github.com/JX3BOX/jx3box-data/blob/master/data/xf/relation.json
mount_belong_school

**Comment by iRuxu** [comment]
## 后端接口

可以使用$node通用请求

GET /cheat
query :
+ school_name  (string)
+ skill_name (string)

见文件内

**Comment by iRuxu** [comment]
## 碑铭

碑铭的展示，请使用

__iconPath + 'map/$map_id.png' 展示图片，并进行标点。
相关json由解包组提供，放在 https://github.com/JX3BOX/bps/tree/master/src/assets/data/beiming 目录下。

讨论issue： https://github.com/JX3BOX/jx3-unpkg/issues/13

**Comment by yjrguxing** [comment]
**心法展示**
秘籍区分从 门派区分 细化为 心法区分
