### ISSUE TITLE
秘籍数据完善

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bps#11]
![image](https://user-images.githubusercontent.com/8476969/134223476-87fef938-a74d-46df-9361-661de44bae75.png)

1. 缺少监本数？
2. 增加icon列，填充秘籍图标

- [x] 已完成

**Comment by iRuxu** [comment]
school_name字段错别字注意修订

**Comment by yjrguxing** [comment]
完成

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/135611033-115cca5b-1ca8-4d08-a2fd-51f920805df8.png)
