### ISSUE TITLE
DPS计算器导航

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bps#20]
后端需求：https://github.com/JX3BOX/jx3box-os/issues/25

写在 views/dps.vue中

**Comment by iRuxu** [comment]
# UI参考
![image](https://user-images.githubusercontent.com/8476969/152914724-ff238b30-ed24-4ad1-8930-e090d837b98c.png)

**Comment by TYguigui** [comment]
基本UI已完成 等待接口做下一步开发

**Comment by TYguigui** [comment]
1.等待后端接口进一步开发
2.该页面左侧已经有心法筛选模块，是否保留表格心法筛选功能（如图）
![image](https://user-images.githubusercontent.com/91440899/153351604-43fb55cc-43da-4c1f-ae7c-4f871429dbde.png)
