### ISSUE TITLE
职业栏目扩展

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bps#37]
## 置顶区
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/8476969/230208272-7f4ff5fc-58d8-45ae-a3c3-181c4aa84fce.png">

增加一个置顶区域，可以参考宏那边。
注意，这个置顶区域和宏一样，当选择到具体某个门派时，就不再展示了。
因为本身各个心法自身会有置顶（现在主要是yunmoer管不过来，到时候安排个人负责一下）

- [x] 已完成

**Comment by iRuxu** [comment]
## 角标扩展
<img width="622" alt="image" src="https://user-images.githubusercontent.com/8476969/230209281-07f1c2f7-fc37-418e-8294-e68832bf7c36.png">

在公共库的Admin里面，这个映射map要改一下。
这样子处理，默认的Admin里，只需要保留原来的主要的4个。
然后添加一个props以支持栏目特殊的marks。
但是因为Admin组件没有直接暴露，所以各个栏目应该是要从Breadcrumb传递进去。所以要改2个组件。
原来那个”已解决“是茶馆用的。
这里bps栏目新增一个`{fallacy:"存在误导性内容"}`
颜色`#c00`

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/8476969/230211905-5019d66e-6106-4688-9315-bf94ff20a3d3.png">

**Comment by iRuxu** [comment]
## 精品区
<img width="287" alt="image" src="https://user-images.githubusercontent.com/8476969/230260882-f2786396-eb95-46ef-aca7-89a684567b31.png">

- [ ] 已完成

**Comment by Kaviilee** [comment]
在新的feature分支
