### ISSUE TITLE
职业源码无界

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bps#42]
<img width="1088" alt="image" src="https://github.com/JX3BOX/bps/assets/8476969/8f8e535f-e76e-44ce-98b9-933ad571d4dc">

新增一个，这里是不在json里的可能

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="697" alt="image" src="https://github.com/JX3BOX/bps/assets/8476969/c83f3d32-dcc4-4c9e-af8a-f963c07b5c74">

这里应该是要build生成的。
你要去jx3-kungfu库里看一下。

点击无界，就拉无界的这个json。

查看，也是查看wujie里的文件。

群里说的

- [ ] 已完成

**Comment by Kaviilee** [comment]
## lua接口
需要支持wujie
`/api/lua/bps/藏剑/移动端_山居剑意.lua?client=wujie`

![image](https://github.com/JX3BOX/bps/assets/25825282/3d35ceca-4762-47e7-b6bc-52af49831ffa)
